name: saveplate
description: "Aplikasi Food Rescue SaveBite."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

 # --- FIREBASE (VERSI BARU YANG LEBIH STABIL) ---
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  
  # --- PENGATUR DATA (State Management) ---
  provider: ^6.0.0

  # --- TAMPILAN (UI) ---
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0       # Biar font tulisan bagus
  intl: ^0.19.0              # Biar bisa format uang (Rp 10.000)
  cached_network_image: ^3.3.0 # Biar gambar loadingnya cepat

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

flutter:
  uses-material-design: true