name: saveplate
description: "Aplikasi Food Rescue SaveBite."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- ALAT WAJIB (DATABASE & LOGIN) ---
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  
  # --- PENGATUR DATA (State Management) ---
  provider: ^6.0.0

  # --- TAMPILAN (UI) ---
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0       # Biar font tulisan bagus
  intl: ^0.19.0              # Biar bisa format uang (Rp 10.000)
  cached_network_image: ^3.3.0 # Biar gambar loadingnya cepat

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true